version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001" 
    volumes:
      - ./backend:/backend 
      - /backend/node_modules 
    environment:
      - NODE_ENV=development 
    restart: unless-stopped 

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/frontend 
      - /frontend/node_modules 
    environment:
      - NODE_ENV=development 
    restart: unless-stopped 
    depends_on:
      - backend 

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped