name: Add Contributor

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  run-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Change File Permissions
        run: chmod +x docs/utils/add_contributor.py

      - name: Run Python Script
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: docs/utils/add_contributor.py

      - name: Commit and Push Changes
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.email "hatfield.69@wright.edu"
          git config --global user.name "ReeseHatfield"
          git add --all
          git commit -m "Add contributor ${PR_AUTHOR}"
          git -c http.extraHeader="AUTHORIZATION: basic $(echo -n x-access-token:${PERSONAL_ACCESS_TOKEN} | base64)" push origin HEAD:main
